# Generated by Django 6.0.6 on 2026-07-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fix_admin_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('bursar', 'Bursar'), ('gate_staff', 'Gate Staff'), ('class_teacher', 'Class Teacher')], default='admin', max_length=20),
        ),
    ]
