# Generated by Django 6.0.6 on 2026-07-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('allowed_ip', models.CharField(blank=True, help_text='IP address of the client server', max_length=45)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_clients',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=30, unique=True)),
                ('payment_code', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('card_printed', models.BooleanField(default=False)),
                ('card_printed_date', models.DateField(blank=True, null=True)),
                ('reprint_count', models.IntegerField(default=0)),
                ('card_version', models.IntegerField(default=1)),
                ('last_reprint_date', models.DateField(blank=True, null=True)),
                ('last_reprint_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('category', models.CharField(choices=[('day', 'Day Scholar'), ('hostel', 'Hostel Student')], default='day', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.cardtemplate')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['admission_number'],
                'indexes': [models.Index(fields=['admission_number'], name='idx_admission_number'), models.Index(fields=['payment_code'], name='idx_payment_code'), models.Index(fields=['status'], name='idx_student_status')],
            },
        ),
    ]
