# Generated by Django 5.0 on 2026-06-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=30, unique=True)),
                ('payment_code', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('card_printed', models.BooleanField(default=False)),
                ('card_printed_date', models.DateField(blank=True, null=True)),
                ('reprint_count', models.IntegerField(default=0)),
                ('last_reprint_date', models.DateField(blank=True, null=True)),
                ('last_reprint_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.cardtemplate')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['admission_number'],
                'indexes': [models.Index(fields=['admission_number'], name='idx_admission_number'), models.Index(fields=['payment_code'], name='idx_payment_code'), models.Index(fields=['status'], name='idx_student_status')],
            },
        ),
    ]
