# Generated by Django 5.0 on 2026-06-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('day', 'Day Scholar'), ('hostel', 'Hostel Student')], default='day', max_length=10),
        ),
    ]
