# Generated by Django 6.0.6 on 2026-07-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('day', 'Day Scholar'), ('hostel', 'Hostel Student')], default='day', max_length=10)),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=10)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fees_structure',
                'ordering': ['academic_year', 'term', 'class_name', 'category'],
                'unique_together': {('class_name', 'category', 'term', 'academic_year')},
            },
        ),
    ]
