# Generated by Django 5.0 on 2026-06-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=10)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fees_structure',
                'ordering': ['academic_year', 'term', 'class_name'],
                'unique_together': {('class_name', 'term', 'academic_year')},
            },
        ),
    ]
