# Generated by Django 5.0 on 2026-06-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['academic_year', 'term', 'class_name', 'category']},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.CharField(choices=[('day', 'Day Scholar'), ('hostel', 'Hostel Student')], default='day', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('class_name', 'category', 'term', 'academic_year')},
        ),
    ]
