# Generated by Django 5.0 on 2026-06-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateField()),
                ('time_out', models.TimeField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('sick', 'Sick'), ('home', 'Home'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=20)),
                ('authorized_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_logs', to='core.student')),
            ],
            options={
                'db_table': 'movement_log',
                'ordering': ['-exit_date', '-time_out'],
                'indexes': [models.Index(fields=['student', 'exit_date'], name='idx_mv_student_date'), models.Index(fields=['exit_date'], name='idx_mv_date')],
            },
        ),
    ]
