"""
Daily email reports for staff based on their roles.
"""
from datetime import date
from django.utils import timezone


def generate_daily_report(user):
    """Generate role-based daily report."""
    today = date.today()
    
    if user.role in ['super_admin', 'admin']:
        return generate_admin_report(today)
    elif user.role == 'bursar':
        return generate_bursar_report(today)
    elif user.role == 'gate_staff':
        return generate_gate_report(today)
    elif user.role == 'class_teacher':
        return generate_teacher_report(user, today)
    
    return None


def generate_admin_report(today):
    """Full school summary for admin."""
    from core.models import Student
    from attendance.models import Attendance, MealViolation
    from movement.models import MovementLog
    from fees.models import FeeStructure
    
    total = Student.objects.filter(status='active').count()
    present = Attendance.objects.filter(scan_date=today).count()
    absent = total - present if total > present else 0
    outside = MovementLog.objects.filter(exit_date=today, time_in__isnull=True).count()
    violations = MealViolation.objects.filter(occurred_at__date=today).count()
    unresolved = MealViolation.objects.filter(resolved=False).count()
    rate = round((present / total * 100), 1) if total > 0 else 0
    
    html = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: #1a237e; padding: 20px; border-radius: 8px 8px 0 0;">
            <h2 style="color: white; margin: 0;">OneCard Daily Report</h2>
            <p style="color: rgba(255,255,255,0.7); margin: 4px 0 0;">{today.strftime('%B %d, %Y')}</p>
        </div>
        
        <div style="background: white; padding: 20px; border: 1px solid #e0e0e0; border-top: none;">
            <h3 style="color: #1a237e;">Attendance Overview</h3>
            <table style="width: 100%; border-collapse: collapse; margin-bottom: 16px;">
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0;">Total Students</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600;">{total:,}</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; color: #2e7d32;">Present Today</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #2e7d32;">{present:,} ({rate}%)</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; color: #c62828;">Absent</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #c62828;">{absent:,}</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; color: #e65100;">Outside Now</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #e65100;">{outside}</td></tr>
            </table>
            
            <h3 style="color: #1a237e;">Meal Alerts</h3>
            <table style="width: 100%; border-collapse: collapse; margin-bottom: 16px;">
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0;">Violations Today</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #e65100;">{violations}</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0;">Unresolved</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #c62828;">{unresolved}</td></tr>
            </table>
        </div>
        
        <div style="text-align: center; padding: 16px; color: #888; font-size: 12px;">
            Generated by OneCard System | Jinja Senior Secondary School
        </div>
    </div>
    """
    return html


def generate_bursar_report(today):
    """Fee-focused report for bursar."""
    from core.models import Student
    from core.services import get_payment_balance
    from fees.models import FeeStructure
    
    students = Student.objects.filter(status='active')
    total_students = students.count()
    
    not_cleared = 0
    total_expected = 0
    total_collected = 0
    
    for s in students[:500]:  # Sample for performance
        paid = float(get_payment_balance(s.payment_code))
        fee = FeeStructure.objects.first()
        total_fee = float(fee.total_fees) if fee else 800000
        balance = total_fee - paid
        
        total_expected += total_fee
        total_collected += paid
        if balance > 0:
            not_cleared += 1
    
    rate = round((total_collected / total_expected * 100), 1) if total_expected > 0 else 0
    
    html = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: #1a237e; padding: 20px; border-radius: 8px 8px 0 0;">
            <h2 style="color: white; margin: 0;">OneCard Fee Report</h2>
            <p style="color: rgba(255,255,255,0.7); margin: 4px 0 0;">{today.strftime('%B %d, %Y')}</p>
        </div>
        
        <div style="background: white; padding: 20px; border: 1px solid #e0e0e0; border-top: none;">
            <h3 style="color: #1a237e;">Fee Summary</h3>
            <table style="width: 100%; border-collapse: collapse;">
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0;">Collection Rate</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600;">{rate}%</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0;">Total Expected</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600;">{total_expected:,.0f} UGX</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; color: #2e7d32;">Total Collected</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #2e7d32;">{total_collected:,.0f} UGX</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; color: #c62828;">Not Cleared</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #c62828;">{not_cleared} students</td></tr>
            </table>
        </div>
        
        <div style="text-align: center; padding: 16px; color: #888; font-size: 12px;">
            Generated by OneCard System | Jinja Senior Secondary School
        </div>
    </div>
    """
    return html


def generate_gate_report(today):
    """Movement summary for gate staff."""
    from attendance.models import Attendance
    from movement.models import MovementLog
    from core.models import Student
    
    total = Student.objects.filter(status='active').count()
    present = Attendance.objects.filter(scan_date=today).count()
    exits = MovementLog.objects.filter(exit_date=today).count()
    still_out = MovementLog.objects.filter(exit_date=today, time_in__isnull=True).count()
    returns = exits - still_out
    
    html = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: #1a237e; padding: 20px; border-radius: 8px 8px 0 0;">
            <h2 style="color: white; margin: 0;">OneCard Gate Report</h2>
            <p style="color: rgba(255,255,255,0.7); margin: 4px 0 0;">{today.strftime('%B %d, %Y')}</p>
        </div>
        
        <div style="background: white; padding: 20px; border: 1px solid #e0e0e0; border-top: none;">
            <h3 style="color: #1a237e;">Movement Summary</h3>
            <table style="width: 100%; border-collapse: collapse;">
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0;">Present Today</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600;">{present:,} / {total:,}</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; color: #e65100;">Exits Today</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #e65100;">{exits}</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; color: #2e7d32;">Returns Today</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #2e7d32;">{returns}</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; color: #c62828;">Still Outside</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #c62828;">{still_out}</td></tr>
            </table>
        </div>
        
        <div style="text-align: center; padding: 16px; color: #888; font-size: 12px;">
            Generated by OneCard System | Jinja Senior Secondary School
        </div>
    </div>
    """
    return html


def generate_teacher_report(user, today):
    """Class-specific report for teacher."""
    from core.models import Student
    from attendance.models import Attendance
    
    assigned_class = user.assigned_class
    assigned_stream = user.assigned_stream
    
    if not assigned_class:
        return None
    
    class_students = Student.objects.filter(status='active')
    # Filter by class if in standalone mode
    class_students = [s for s in class_students if hasattr(s, 'current_class') and s.current_class == assigned_class]
    if assigned_stream:
        class_students = [s for s in class_students if hasattr(s, 'stream') and s.stream == assigned_stream]
    
    total = len(class_students)
    student_ids = [s.id for s in class_students]
    present = Attendance.objects.filter(student_id__in=student_ids, scan_date=today).count()
    absent = total - present if total > present else 0
    rate = round((present / total * 100), 1) if total > 0 else 0
    
    html = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: #1a237e; padding: 20px; border-radius: 8px 8px 0 0;">
            <h2 style="color: white; margin: 0;">OneCard Class Report</h2>
            <p style="color: rgba(255,255,255,0.7); margin: 4px 0 0;">{assigned_class} {assigned_stream or ''} | {today.strftime('%B %d, %Y')}</p>
        </div>
        
        <div style="background: white; padding: 20px; border: 1px solid #e0e0e0; border-top: none;">
            <h3 style="color: #1a237e;">Attendance Summary</h3>
            <table style="width: 100%; border-collapse: collapse;">
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0;">Total Students</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600;">{total}</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; color: #2e7d32;">Present</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #2e7d32;">{present} ({rate}%)</td></tr>
                <tr><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; color: #c62828;">Absent</td><td style="padding: 8px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: 600; color: #c62828;">{absent}</td></tr>
            </table>
        </div>
        
        <div style="text-align: center; padding: 16px; color: #888; font-size: 12px;">
            Generated by OneCard System | Jinja Senior Secondary School
        </div>
    </div>
    """
    return html