# Generated by Django 5.0 on 2026-06-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IMPORT', 'Import'), ('SCAN', 'Scan'), ('PRINT', 'Print'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_class', models.CharField(max_length=20)),
                ('to_class', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('promoted', 'Promoted'), ('repeated', 'Repeated'), ('demoted', 'Demoted')], max_length=20)),
                ('academic_year', models.CharField(max_length=10)),
                ('processed_by', models.CharField(max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'promotion_history',
                'ordering': ['-processed_at'],
            },
        ),
    ]
