# Generated by Django 6.0.6 on 2026-07-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardReprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reprint_number', models.IntegerField()),
                ('reason', models.CharField(choices=[('lost', 'Lost'), ('damaged', 'Damaged'), ('correction', 'Data Correction'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reprinted_by', models.CharField(max_length=50)),
                ('reprinted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'card_reprints',
                'ordering': ['-reprinted_at'],
            },
        ),
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_level', models.CharField(choices=[('O', "O'LEVEL"), ('A', "A'LEVEL")], max_length=1)),
                ('color_name', models.CharField(max_length=30)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('border_color', models.CharField(default='#000000', max_length=7)),
                ('border_style', models.CharField(choices=[('solid', 'Solid'), ('dashed', 'Dashed'), ('double', 'Double')], default='solid', max_length=20)),
                ('accent_color', models.CharField(default='#000000', max_length=7)),
                ('badge_text', models.CharField(default="O'LEVEL", max_length=20)),
                ('badge_color', models.CharField(default='#000000', max_length=7)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'card_templates',
                'ordering': ['class_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassTemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=10)),
                ('assigned_by', models.CharField(max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'class_template_assignments',
            },
        ),
    ]
