# Generated by Django 5.0 on 2026-06-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardreprint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprints', to='core.student'),
        ),
        migrations.AddField(
            model_name='classtemplateassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='classtemplateassignment',
            unique_together={('class_name', 'academic_year')},
        ),
    ]
