# Generated by Django 5.0 on 2026-06-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_balance_threshold', models.DecimalField(decimal_places=2, default=500000, max_digits=10)),
                ('fee_zero_payment_week', models.IntegerField(default=4)),
                ('attendance_consecutive_days', models.IntegerField(default=3)),
                ('attendance_weekly_days', models.IntegerField(default=5)),
                ('attendance_term_percentage', models.IntegerField(default=75)),
                ('movement_hours_outside', models.IntegerField(default=3)),
                ('movement_exits_per_day', models.IntegerField(default=3)),
                ('show_in_dashboard', models.BooleanField(default=True)),
                ('email_alerts', models.BooleanField(default=False)),
                ('email_recipient', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('fee', 'Fees'), ('attendance', 'Attendance'), ('movement', 'Movement'), ('system', 'System')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
