# Generated by Django 5.0 on 2026-06-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='late_cutoff_time',
            field=models.TimeField(default='08:00', help_text='Students arriving after this time are marked Late'),
        ),
    ]
