# Generated by Django 5.0 on 2026-06-17 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsetting_late_cutoff_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_3_consecutive_absences', models.BooleanField(default=True, help_text='Alert when a student is absent 3+ consecutive days')),
                ('alert_attendance_below_75', models.BooleanField(default=True, help_text='Alert when class attendance drops below 75%')),
                ('alert_5_absences_term', models.BooleanField(default=True, help_text='Alert when a student has 5+ absences this term')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notif_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_notification_settings',
            },
        ),
    ]
