# Generated by Django 5.0 on 2026-06-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField()),
                ('time_in', models.TimeField()),
                ('scan_location', models.CharField(max_length=50)),
                ('marked_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-scan_date', '-time_in'],
            },
        ),
        migrations.CreateModel(
            name='ScanLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, unique=True)),
                ('default_mode', models.CharField(choices=[('attendance_balance', 'Attendance + Balance'), ('balance_only', 'Balance Only'), ('pass_out', 'Pass Out / Return'), ('full_info', 'Full Info (No Log)')], default='attendance_balance', max_length=30)),
                ('status', models.CharField(default='active', max_length=10)),
            ],
            options={
                'db_table': 'scan_locations',
                'ordering': ['location_name'],
            },
        ),
    ]
