# Generated by Django 6.0.6 on 2026-07-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField()),
                ('time_in', models.TimeField()),
                ('scan_location', models.CharField(max_length=50)),
                ('marked_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-scan_date', '-time_in'],
            },
        ),
        migrations.CreateModel(
            name='MealAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('day', 'Day Scholar'), ('hostel', 'Hostel Student')], max_length=10)),
                ('max_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meal_access_rules',
                'ordering': ['academic_year', 'term', 'class_name', 'category'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('supper', 'Supper')], max_length=10)),
                ('time_scanned', models.TimeField()),
                ('location', models.CharField(default='Dining Hall', max_length=50)),
                ('marked_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meal_logs',
                'ordering': ['-meal_date', '-time_scanned'],
            },
        ),
        migrations.CreateModel(
            name='MealTimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_start', models.TimeField(default='07:00')),
                ('breakfast_end', models.TimeField(default='08:30')),
                ('lunch_start', models.TimeField(default='12:30')),
                ('lunch_end', models.TimeField(default='14:00')),
                ('supper_start', models.TimeField(default='18:00')),
                ('supper_end', models.TimeField(default='19:30')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meal_time_settings',
            },
        ),
        migrations.CreateModel(
            name='MealViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('supper', 'Supper')], max_length=10)),
                ('violation_type', models.CharField(choices=[('double_serving', 'Double Serving Attempt'), ('day_supper', 'Day Scholar - Supper Attempt'), ('day_breakfast', 'Day Scholar - Breakfast Attempt'), ('balance_high', 'Balance Above Threshold'), ('outside_time', 'Outside Meal Time')], max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meal_violations',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, unique=True)),
                ('default_mode', models.CharField(choices=[('attendance_balance', 'Attendance + Balance'), ('balance_only', 'Balance Only'), ('pass_out', 'Pass Out / Return'), ('full_info', 'Full Info (No Log)')], default='attendance_balance', max_length=30)),
                ('status', models.CharField(default='active', max_length=10)),
            ],
            options={
                'db_table': 'scan_locations',
                'ordering': ['location_name'],
            },
        ),
    ]
