# Generated by Django 6.0.6 on 2026-07-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student'),
        ),
        migrations.AlterUniqueTogether(
            name='mealaccessrule',
            unique_together={('class_name', 'category', 'term', 'academic_year')},
        ),
        migrations.AddField(
            model_name='meallog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='core.student'),
        ),
        migrations.AddField(
            model_name='mealviolation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_violations', to='core.student'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'scan_date'], name='idx_att_student_date'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['scan_date'], name='idx_att_date'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'scan_date')},
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['student', 'meal_date', 'meal_type'], name='idx_meal_student_date_type'),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['meal_date', 'meal_type'], name='idx_meal_date_type'),
        ),
        migrations.AlterUniqueTogether(
            name='meallog',
            unique_together={('student', 'meal_date', 'meal_type')},
        ),
    ]
