# Generated by Django 5.0 on 2026-06-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'scan_date'], name='idx_att_student_date'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['scan_date'], name='idx_att_date'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'scan_date')},
        ),
    ]
