# Generated by Django 5.0 on 2026-06-12 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('core', '0004_student_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('supper', 'Supper')], max_length=10)),
                ('time_scanned', models.TimeField()),
                ('location', models.CharField(default='Dining Hall', max_length=50)),
                ('marked_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='core.student')),
            ],
            options={
                'db_table': 'meal_logs',
                'ordering': ['-meal_date', '-time_scanned'],
                'indexes': [models.Index(fields=['student', 'meal_date', 'meal_type'], name='idx_meal_student_date_type'), models.Index(fields=['meal_date', 'meal_type'], name='idx_meal_date_type')],
                'unique_together': {('student', 'meal_date', 'meal_type')},
            },
        ),
    ]
