# Generated by Django 5.0 on 2026-06-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_meallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('day', 'Day Scholar'), ('hostel', 'Hostel Student')], max_length=10)),
                ('max_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meal_access_rules',
                'ordering': ['academic_year', 'term', 'class_name', 'category'],
                'unique_together': {('class_name', 'category', 'term', 'academic_year')},
            },
        ),
    ]
