# Generated by Django 5.0 on 2026-06-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_mealaccessrule'),
        ('core', '0005_alter_student_created_at_alter_student_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_start', models.TimeField(default='07:00')),
                ('breakfast_end', models.TimeField(default='08:30')),
                ('lunch_start', models.TimeField(default='12:30')),
                ('lunch_end', models.TimeField(default='14:00')),
                ('supper_start', models.TimeField(default='18:00')),
                ('supper_end', models.TimeField(default='19:30')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meal_time_settings',
            },
        ),
        migrations.CreateModel(
            name='MealViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('supper', 'Supper')], max_length=10)),
                ('violation_type', models.CharField(choices=[('double_serving', 'Double Serving Attempt'), ('day_supper', 'Day Scholar - Supper Attempt'), ('day_breakfast', 'Day Scholar - Breakfast Attempt'), ('balance_high', 'Balance Above Threshold'), ('outside_time', 'Outside Meal Time')], max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_violations', to='core.student')),
            ],
            options={
                'db_table': 'meal_violations',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
